from .home import home
from .auth.login import login
from .auth.logout import logout_user
from .auth.register import register_user
from .user_login import user_login
from .events.details import event_details
from .events.form import event_form
from .events.list import event_list
from .streams.details import stream_details